# my_string=input("Введите Ваше имя: ")
# current_year=2024
# date_of_birth=input("В каком году Вы родились? ")
# age=current_year-int(date_of_birth)
# print("Здравствуйте, ",my_string)
# print("В этом году Вам ", age, 'лет')
# print('привет, я строка в нижнем регистре'.upper().lower())
# print('привет, я строка в нижнем регистре'.replace(' ','#'))
my_string=input("Введите наименование урока: ")
print(len(my_string))
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ',''))
print(my_string[0])
print(my_string[-1])